# Generated by Django 5.0 on 2024-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_slot_number_bookedevent_slot_availableslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSlot',
            new_name='BookedSlot',
        ),
    ]
