# Generated by Django 5.0 on 2024-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedevent',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='event_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
