# Generated by Django 5.0 on 2024-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_bookedevent_event_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedevent',
            name='amount_paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='attempt',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='created_at',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='razor_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
