# Generated by Django 5.0 on 2024-03-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='card_field/'),
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
    ]
