# Generated by Django 5.0 on 2024-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_event_images_alter_event_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='card_field/'),
        ),
        migrations.AddField(
            model_name='event',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='card_field/'),
        ),
        migrations.AddField(
            model_name='event',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='card_field/'),
        ),
        migrations.AddField(
            model_name='event',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='card_field/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(help_text='THis is the cover pictuer and required', upload_to='card_field/'),
        ),
    ]
