# Generated by Django 5.0 on 2024-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedevent',
            name='amount_due',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='amount_paid',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='attempt',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='created_at',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='razor_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
