# Generated by Django 5.0 on 2024-03-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_history_amount_due_history_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set(),
        ),
    ]
